### ISSUE TITLE
why no android?

### ISSUE THREAD

**Issue by barron9** [asrytis/dice-game#2]
why no android?

**Comment by asrytis** [comment]
I didn't have much luck with Android Studio on OS X and never tried setting it up again

**Comment by barron9** [comment]
actually it will work good,
and one thing i can't run on iOS it gives error like this with same cloned project here

undefined is not an object evaluating _reactnative.viewproptypes.style

**Comment by asrytis** [comment]
caused by outdated dependencies. I'll try and see if I can fix this within the next hour.

**Comment by asrytis** [comment]
I updated all dependencies which fixed the issue. I also added support for Android although I I'm not sure I will want to maintain that. You can find it on the branch:
https://github.com/asrytis/dice-game/tree/fix/launch-error

I was unable to update eslint easily, will do it tomorrow maybe.
